shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - undici@6.22.0
  - undici-types@6.21.0
packages:
  - packages/*
catalogs:
  default:
    '@antfu/eslint-config': ^9.0.0
    '@release-it/conventional-changelog': ^11.0.0
    '@tailwindcss/vite': ^4.3.0
    '@types/node': ^25.9.1
    '@vitejs/plugin-vue': ^6.0.7
    '@vitest/coverage-v8': ^4.1.7
    '@vitest/ui': ^4.1.7
    '@vue/compiler-dom': ^3.5.34
    '@vue/test-utils': ^2.4.10
    '@vue/tsconfig': ^0.9.1
    browserslist: ^4.28.2
    daisyui: ^5.5.20
    eslint: ^10.4.0
    eslint-plugin-vuejs-accessibility: ^2.5.0
    jsdom: ^29.1.1
    lightningcss: ^1.32.0
    release-it: ^20.0.1
    shiki: ^4.1.0
    tailwindcss: ^4.3.0
    typescript: ^6.0.3
    vike: ^0.4.259
    vike-vue: ^0.9.11
    vite: ^8.0.14
    vite-plugin-dts: ^5.0.1
    vitest: ^4.1.7
    vue: ^3.5.34
    vue-tsc: ^3.3.1
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
