shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - undici@6.22.0
  - undici-types@6.21.0
packages:
  - packages/*
catalogs:
  default:
    '@antfu/eslint-config': ^7.2.0
    '@release-it/conventional-changelog': ^10.0.4
    '@tailwindcss/vite': ^4.1.18
    '@types/node': ^25.0.10
    '@vitejs/plugin-vue': ^6.0.3
    '@vitest/coverage-v8': ^4.0.18
    '@vitest/ui': ^4.0.18
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    daisyui: ^5.5.14
    eslint: ^9.39.2
    eslint-plugin-vuejs-accessibility: ^2.4.1
    jsdom: ^27.4.0
    release-it: ^19.2.4
    shikiji: ^0.10.2
    tailwindcss: ^4.1.18
    typescript: ^5.9.3
    vike: ^0.4.252
    vike-vue: ^0.9.9
    vite: npm:rolldown-vite@^7.3.1
    vite-plugin-dts: ^4.5.4
    vitest: ^4.0.18
    vue: 3.6.0-beta.3
    vue-tsc: ^3.2.3
onlyBuiltDependencies:
  - esbuild
