import { existsSync, readFileSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { build } from 'vite';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const pkgRoot = resolve(__dirname, '..');
const distDir = resolve(pkgRoot, 'dist');

interface ManifestExport {
  types?: string;
  import?: string;
  require?: string;
}

interface Manifest {
  types?: string;
  main?: string;
  module?: string;
  unpkg?: string;
  jsdelivr?: string;
  exports?: Record<string, string | ManifestExport>;
}

beforeAll(async () => {
  rmSync(distDir, { recursive: true, force: true });
  // pin root: vitest workers run from the repo root, and vite derives root from cwd
  await build({ configFile: resolve(pkgRoot, 'vite.config.ts'), root: pkgRoot, logLevel: 'silent' });
  await build({ configFile: resolve(pkgRoot, 'vite.config.core.ts'), root: pkgRoot, logLevel: 'silent' });
  await build({ configFile: resolve(pkgRoot, 'vite.config.umd.ts'), root: pkgRoot, logLevel: 'silent' });
}, 120_000);

afterAll(() => {
  rmSync(distDir, { recursive: true, force: true });
});

describe('build output layout', () => {
  it('emits the entry declaration at dist/index.d.ts', () => {
    expect(existsSync(resolve(distDir, 'index.d.ts'))).toBe(true);
  });

  it('does not nest declarations under dist/src', () => {
    expect(existsSync(resolve(distDir, 'src'))).toBe(false);
  });

  it('emits module declarations relative to the dist root', () => {
    expect(existsSync(resolve(distDir, 'composables/useVirtualScroll.d.ts'))).toBe(true);
    expect(existsSync(resolve(distDir, 'components/VirtualScroll.vue.d.ts'))).toBe(true);
  });

  it('emits the internal engine entry', () => {
    expect(existsSync(resolve(distDir, 'internal.mjs'))).toBe(true);
    expect(existsSync(resolve(distDir, 'internal.cjs'))).toBe(true);
    expect(existsSync(resolve(distDir, 'internal.d.ts'))).toBe(true);
  });

  it('emits the CDN bundle', () => {
    expect(existsSync(resolve(distDir, 'index.js'))).toBe(true);
  });

  it('keeps the engine internals out of the public entry declarations', () => {
    const publicTypes = readFileSync(resolve(distDir, 'index.d.ts'), 'utf8');
    const internalTypes = readFileSync(resolve(distDir, 'internal.d.ts'), 'utf8');

    expect(internalTypes).toContain('\'./utils/virtual-scroll-logic\'');
    expect(publicTypes).not.toContain('virtual-scroll-logic');
    expect(publicTypes).not.toContain('ScrollTargetParams');

    // The sizing layer is a sub-layer of the engine: internal entry only.
    expect(internalTypes).toContain('\'./composables/useVirtualScrollSizes\'');
    expect(publicTypes).not.toContain('useVirtualScrollSizes');

    // ...but the structure it builds on stays public.
    expect(publicTypes).toContain('fenwick-tree');
  });

  it('publishes the engine internals from the internal bundle', async () => {
    // Dynamic on purpose: the bundle is generated by beforeAll, so it cannot be
    // a static import - and this is the only check on the *built* entry resolving.
    const internals = await import(pathToFileURL(resolve(distDir, 'internal.mjs')).href) as Record<string, unknown>;

    expect(typeof internals.calculateRange).toBe('function');
    expect(typeof internals.displayToVirtual).toBe('function');
    expect(typeof internals.MasonryLayout).toBe('function');
    expect(typeof internals.useVirtualScrollSizes).toBe('function');
  });

  it('keeps every dist path declared in the manifest present in the build output', () => {
    const manifest = JSON.parse(readFileSync(resolve(pkgRoot, 'package.json'), 'utf8')) as Manifest;
    const entries: Array<ManifestExport | string | undefined> = [
      manifest.types,
      manifest.main,
      manifest.module,
      manifest.unpkg,
      manifest.jsdelivr,
      ...Object.values(manifest.exports ?? {}),
    ];
    const declaredDistPaths = entries
      .flatMap((entry) => (typeof entry === 'string' ? [ entry ] : [ entry?.types, entry?.import, entry?.require ]))
      .filter((path): path is string => typeof path === 'string' && path.startsWith('./dist'));
    expect(declaredDistPaths.length).toBeGreaterThan(0);
    for (const path of declaredDistPaths) {
      expect(existsSync(resolve(pkgRoot, path)), `missing built file ${ path }`).toBe(true);
    }
  });
});
